language: cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - cd build && cmake ../tests && make && make test
after_success:
  - coveralls --exclude tests -r .. -b . --gcov-options '\-lp'